version: "3.9"

services:
  sagsin-fe:
    image: baocules/sagsin-fe
    container_name: sagsin-fe
    ports:
      - "5173:80"
  # Backend Service
  sagsin-backend:
    image: baocules/sagsin-be
    container_name: sagsin-be
    networks:
      topo_net:
        ipv4_address: 192.168.100.10
    ports:
      - "3000:3000"
      - "50051:50051"
      - "50053:50053"
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
      - GRPC_URL=0.0.0.0:50051
      - TIMELINE_GRPC_PORT=0.0.0.0:50053
      - DATABASE_URL=mongodb://mongodb:27017/sagsin-db
      - HEURISTIC_URL=192.168.100.3:50052
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  sagsin-heuristic:
    image: baocules/sagsin-heuristic
    container_name: sagsin-heuristic
    networks:
      topo_net:
        ipv4_address: 192.168.100.3
    environment:
      - BACKEND_SOCKET_URL=http://sagsin-be:3000
    depends_on:
      sagsin-backend:
        condition: service_healthy

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      topo_net:
        ipv4_address: 192.168.100.2
    environment:
      - MONGO_INITDB_DATABASE=sagsin-db

  satellite_nairobi:
    image: baocules/sagsin-agent
    container_name: satellite_nairobi
    environment:
      - HOST_NAME=satellite_nairobi
      - LAT=-1.2921
      - LNG=36.8219
    networks:
      topo_net:
        ipv4_address: 192.168.100.11
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  satellite_sao_paulo:
    image: baocules/sagsin-agent
    container_name: satellite_sao_paulo
    environment:
      - HOST_NAME=satellite_sao_paulo
      - LAT=-23.5505
      - LNG=-46.6333
    networks:
      topo_net:
        ipv4_address: 192.168.100.12
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_beijing:
    image: baocules/sagsin-agent
    container_name: drone_beijing
    environment:
      - HOST_NAME=drone_beijing
      - LAT=39.9042
      - LNG=116.4074
    networks:
      topo_net:
        ipv4_address: 192.168.100.21
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_mumbai:
    image: baocules/sagsin-agent
    container_name: drone_mumbai
    environment:
      - HOST_NAME=drone_mumbai
      - LAT=19.0760
      - LNG=72.8777
    networks:
      topo_net:
        ipv4_address: 192.168.100.22
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_london:
    image: baocules/sagsin-agent
    container_name: drone_london
    environment:
      - HOST_NAME=drone_london
      - LAT=51.5074
      - LNG=-0.1278
    networks:
      topo_net:
        ipv4_address: 192.168.100.23
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_hanoi:
    image: baocules/sagsin-agent
    container_name: ground_station_hanoi
    environment:
      - HOST_NAME=ground_station_hanoi
      - LAT=21.0285
      - LNG=105.8542
    networks:
      topo_net:
        ipv4_address: 192.168.100.31
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_paris:
    image: baocules/sagsin-agent
    container_name: ground_station_paris
    environment:
      - HOST_NAME=ground_station_paris
      - LAT=48.8566
      - LNG=2.3522
    networks:
      topo_net:
        ipv4_address: 192.168.100.32
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_moscow:
    image: baocules/sagsin-agent
    container_name: ground_station_moscow 
    environment:
      - HOST_NAME=ground_station_moscow
      - LAT=55.7558
      - LNG=37.6173
    networks:
      topo_net:
        ipv4_address: 192.168.100.33
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_tokyo:
    image: baocules/sagsin-agent
    container_name: mobile_device_tokyo
    environment:
      - HOST_NAME=mobile_device_tokyo
      - LAT=35.6764
      - LNG=139.6500
    networks:
      topo_net:
        ipv4_address: 192.168.100.34
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_riyadh:
    image: baocules/sagsin-agent
    container_name: mobile_device_riyadh
    environment:
      - HOST_NAME=mobile_device_riyadh
      - LAT=24.7136
      - LNG=46.6753
    networks:
      topo_net:
        ipv4_address: 192.168.100.35
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_newyork:
    image: baocules/sagsin-agent
    container_name: mobile_device_newyork
    environment:
      - HOST_NAME=mobile_device_newyork
      - LAT=40.7128
      - LNG=-74.0060
    networks:
      topo_net:
        ipv4_address: 192.168.100.36
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_singapore:
    image: baocules/sagsin-agent
    container_name: mobile_device_singapore
    environment:
      - HOST_NAME=mobile_device_singapore
      - LAT=1.3521
      - LNG=103.8198
    networks:
      topo_net:
        ipv4_address: 192.168.100.37
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_singapore:
    image: baocules/sagsin-agent
    container_name: ship_singapore
    environment:
      - HOST_NAME=ship_singapore
      - LAT=1.5321
      - LNG=104.2
    networks:
      topo_net:
        ipv4_address: 192.168.100.41
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_tokyo:
    image: baocules/sagsin-agent
    container_name: ship_tokyo
    environment:
      - HOST_NAME=ship_tokyo
      - LAT=35.0
      - LNG=141.0
    networks:
      topo_net:
        ipv4_address: 192.168.100.42
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_london:
    image: baocules/sagsin-agent
    container_name: ship_london
    environment:
      - HOST_NAME=ship_london
      - LAT=51.0
      - LNG=1.5
    networks:
      topo_net:
        ipv4_address: 192.168.100.43
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

networks:
  topo_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24