version: "3.9"

services:
  sagsin-fe:
    image: baocules/sagsin-fe
    container_name: sagsin-fe
    ports:
      - "5173:80"
  # Backend Service
  sagsin-backend:
    image: baocules/sagsin-be
    container_name: sagsin-be
    networks:
      topo_net:
        ipv4_address: 192.168.100.10
    ports:
      - "3000:3000"
      - "50051:50051"
      - "50053:50053"
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
      - GRPC_URL=0.0.0.0:50051
      - TIMELINE_GRPC_PORT=0.0.0.0:50053
      - DATABASE_URL=mongodb://mongodb:27017/sagsin-db
      - HEURISTIC_URL=192.168.100.3:50052
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  sagsin-heuristic:
    image: baocules/sagsin-heuristic
    container_name: sagsin-heuristic
    networks:
      topo_net:
        ipv4_address: 192.168.100.3
    environment:
      - BACKEND_SOCKET_URL=http://sagsin-be:3000
    depends_on:
      sagsin-backend:
        condition: service_healthy

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      topo_net:
        ipv4_address: 192.168.100.2
    environment:
      - MONGO_INITDB_DATABASE=sagsin-db

  satellite_nairobi:
    image: baocules/sagsin-agent
    container_name: satellite_nairobi
    environment:
      - HOST_NAME=satellite_nairobi
      - LAT=-1.2921
      - LNG=36.8219
      - WEATHER=clear
    networks:
      topo_net:
        ipv4_address: 192.168.100.11
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  satellite_sao_paulo:
    image: baocules/sagsin-agent
    container_name: satellite_sao_paulo
    environment:
      - HOST_NAME=satellite_sao_paulo
      - LAT=-23.5505
      - LNG=-46.6333
      - WEATHER=rainy
    networks:
      topo_net:
        ipv4_address: 192.168.100.12
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_beijing:
    image: baocules/sagsin-agent
    container_name: drone_beijing
    environment:
      - HOST_NAME=drone_beijing
      - LAT=39.9042
      - LNG=116.4074
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.21
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_mumbai:
    image: baocules/sagsin-agent
    container_name: drone_mumbai
    environment:
      - HOST_NAME=drone_mumbai
      - LAT=19.0760
      - LNG=72.8777
      - WEATHER=rainy
    networks:
      topo_net:
        ipv4_address: 192.168.100.22
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_london:
    image: baocules/sagsin-agent
    container_name: drone_london
    environment:
      - HOST_NAME=drone_london
      - LAT=51.5074
      - LNG=-0.1278
      - WEATHER=rainy
    networks:
      topo_net:
        ipv4_address: 192.168.100.23
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_hanoi:
    image: baocules/sagsin-agent
    container_name: ground_station_hanoi
    environment:
      - HOST_NAME=ground_station_hanoi
      - LAT=21.0285
      - LNG=105.8542
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.31
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_paris:
    image: baocules/sagsin-agent
    container_name: ground_station_paris
    environment:
      - HOST_NAME=ground_station_paris
      - LAT=48.8566
      - LNG=2.3522
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.32
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_moscow:
    image: baocules/sagsin-agent
    container_name: ground_station_moscow 
    environment:
      - HOST_NAME=ground_station_moscow
      - LAT=55.7558
      - LNG=37.6173
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.33
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_tokyo:
    image: baocules/sagsin-agent
    container_name: mobile_device_tokyo
    environment:
      - HOST_NAME=mobile_device_tokyo
      - LAT=35.6764
      - LNG=139.6500
      - WEATHER=clear
    networks:
      topo_net:
        ipv4_address: 192.168.100.34
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_riyadh:
    image: baocules/sagsin-agent
    container_name: mobile_device_riyadh
    environment:
      - HOST_NAME=mobile_device_riyadh
      - LAT=24.7136
      - LNG=46.6753
      - WEATHER=clear
    networks:
      topo_net:
        ipv4_address: 192.168.100.35
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_newyork:
    image: baocules/sagsin-agent
    container_name: mobile_device_newyork
    environment:
      - HOST_NAME=mobile_device_newyork
      - LAT=40.7128
      - LNG=-74.0060
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.36
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_singapore:
    image: baocules/sagsin-agent
    container_name: mobile_device_singapore
    environment:
      - HOST_NAME=mobile_device_singapore
      - LAT=1.3521
      - LNG=103.8198
      - WEATHER=rainy
    networks:
      topo_net:
        ipv4_address: 192.168.100.37
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_singapore:
    image: baocules/sagsin-agent
    container_name: ship_singapore
    environment:
      - HOST_NAME=ship_singapore
      - LAT=1.5321
      - LNG=104.2
      - WEATHER=stormy
    networks:
      topo_net:
        ipv4_address: 192.168.100.41
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_tokyo:
    image: baocules/sagsin-agent
    container_name: ship_tokyo
    environment:
      - HOST_NAME=ship_tokyo
      - LAT=35.0
      - LNG=141.0
      - WEATHER=rainy
    networks:
      topo_net:
        ipv4_address: 192.168.100.42
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_london:
    image: baocules/sagsin-agent
    container_name: ship_london
    environment:
      - HOST_NAME=ship_london
      - LAT=51.0
      - LNG=1.5
      - WEATHER=stormy
    networks:
      topo_net:
        ipv4_address: 192.168.100.43
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  satellite_sydney:
    image: baocules/sagsin-agent
    container_name: satellite_sydney
    environment:
      - HOST_NAME=satellite_sydney
      - LAT=-33.8688
      - LNG=151.2093
      - WEATHER=clear
    networks:
      topo_net:
        ipv4_address: 192.168.100.13
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_capetown:
    image: baocules/sagsin-agent
    container_name: drone_capetown
    environment:
      - HOST_NAME=drone_capetown
      - LAT=-33.9249
      - LNG=18.4241
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.24
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  drone_toronto:
    image: baocules/sagsin-agent
    container_name: drone_toronto
    environment:
      - HOST_NAME=drone_toronto
      - LAT=43.6532
      - LNG=-79.3832
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.25
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_cairo:
    image: baocules/sagsin-agent
    container_name: ground_station_cairo
    environment:
      - HOST_NAME=ground_station_cairo
      - LAT=30.0444
      - LNG=31.2357
      - WEATHER=clear
    networks:
      topo_net:
        ipv4_address: 192.168.100.38
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ground_station_jakarta:
    image: baocules/sagsin-agent
    container_name: ground_station_jakarta
    environment:
      - HOST_NAME=ground_station_jakarta
      - LAT=-6.2088
      - LNG=106.8456
      - WEATHER=rainy
    networks:
      topo_net:
        ipv4_address: 192.168.100.39
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_dubai:
    image: baocules/sagsin-agent
    container_name: mobile_device_dubai
    environment:
      - HOST_NAME=mobile_device_dubai
      - LAT=25.2048
      - LNG=55.2708
      - WEATHER=clear
    networks:
      topo_net:
        ipv4_address: 192.168.100.44
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_berlin:
    image: baocules/sagsin-agent
    container_name: mobile_device_berlin
    environment:
      - HOST_NAME=mobile_device_berlin
      - LAT=52.5200
      - LNG=13.4050
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.45
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  mobile_device_seoul:
    image: baocules/sagsin-agent
    container_name: mobile_device_seoul
    environment:
      - HOST_NAME=mobile_device_seoul
      - LAT=37.5665
      - LNG=126.9780
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.46
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_miami:
    image: baocules/sagsin-agent
    container_name: ship_miami
    environment:
      - HOST_NAME=ship_miami
      - LAT=25.7617
      - LNG=-80.1918
      - WEATHER=rainy
    networks:
      topo_net:
        ipv4_address: 192.168.100.47
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

  ship_vancouver:
    image: baocules/sagsin-agent
    container_name: ship_vancouver
    environment:
      - HOST_NAME=ship_vancouver
      - LAT=49.2827
      - LNG=-123.1207
      - WEATHER=cloudy
    networks:
      topo_net:
        ipv4_address: 192.168.100.48
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro
    depends_on:
      sagsin-backend:
        condition: service_healthy

networks:
  topo_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24