version: "3.9"

services:
  satellite_tokyo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: satellite_tokyo
    networks:
      topo_net:
        ipv4_address: 192.168.100.11
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  satellite_newyork:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: satellite_newyork
    networks:
      topo_net:
        ipv4_address: 192.168.100.12
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  drone_beijing:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: drone_beijing
    networks:
      topo_net:
        ipv4_address: 192.168.100.21
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  drone_mumbai:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: drone_mumbai
    networks:
      topo_net:
        ipv4_address: 192.168.100.22
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  drone_london:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: drone_london
    networks:
      topo_net:
        ipv4_address: 192.168.100.23
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  ground_station_hanoi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: ground_station_hanoi
    networks:
      topo_net:
        ipv4_address: 192.168.100.31
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  ground_station_paris:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: ground_station_paris
    networks:
      topo_net:
        ipv4_address: 192.168.100.32
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  ground_station_moscow:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: ground_station_moscow
    networks:
      topo_net:
        ipv4_address: 192.168.100.33
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  mobile_device_tokyo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: mobile_device_tokyo
    networks:
      topo_net:
        ipv4_address: 192.168.100.34
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  mobile_device_london:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: mobile_device_london
    networks:
      topo_net:
        ipv4_address: 192.168.100.35
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  mobile_device_newyork:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: mobile_device_newyork
    networks:
      topo_net:
        ipv4_address: 192.168.100.36
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  mobile_device_singapore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: mobile_device_singapore
    networks:
      topo_net:
        ipv4_address: 192.168.100.37
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  ship_singapore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: ship_singapore
    networks:
      topo_net:
        ipv4_address: 192.168.100.41
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  ship_tokyo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: ship_tokyo
    networks:
      topo_net:
        ipv4_address: 192.168.100.42
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

  ship_london:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: ship_london
    networks:
      topo_net:
        ipv4_address: 192.168.100.43
    volumes:
      - ./custom_hosts:/etc/hosts
    restart: unless-stopped

networks:
  topo_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
