version: "3.9"

services:
  # Backend Service
  sagsin-backend:
    image: baocules/sagsin-be
    container_name: sagsin-be
    networks:
      topo_net:
        ipv4_address: 192.168.100.10
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
      - GRPC_URL=0.0.0.0:50051
      - DATABASE_URL=mongodb://mongodb:27017/sagsin-db
      - HEURISTIC_URL=192.168.100.3:50052
    depends_on:
      - mongodb
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  sagsin-heuristic:
    image: baocules/sagsin-heuristic
    container_name: sagsin-heuristic
    networks:
      topo_net:
        ipv4_address: 192.168.100.3

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      topo_net:
        ipv4_address: 192.168.100.2
    environment:
      - MONGO_INITDB_DATABASE=sagsin-db

  satellite_tokyo:
    image: baocules/sagsin-agent
    container_name: satellite_tokyo
    environment:
      - HOST_NAME=satellite_tokyo
    networks:
      topo_net:
        ipv4_address: 192.168.100.11
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  satellite_newyork:
    image: baocules/sagsin-agent
    container_name: satellite_newyork
    environment:
      - HOST_NAME=satellite_newyork
    networks:
      topo_net:
        ipv4_address: 192.168.100.12
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  drone_beijing:
    image: baocules/sagsin-agent
    container_name: drone_beijing
    environment:
      - HOST_NAME=drone_beijing
    networks:
      topo_net:
        ipv4_address: 192.168.100.21
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  drone_mumbai:
    image: baocules/sagsin-agent
    container_name: drone_mumbai
    environment:
      - HOST_NAME=drone_mumbai
    networks:
      topo_net:
        ipv4_address: 192.168.100.22
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  drone_london:
    image: baocules/sagsin-agent
    container_name: drone_london
    environment:
      - HOST_NAME=drone_london
    networks:
      topo_net:
        ipv4_address: 192.168.100.23
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  ground_station_hanoi:
    image: baocules/sagsin-agent
    container_name: ground_station_hanoi
    environment:
      - HOST_NAME=ground_station_hanoi
    networks:
      topo_net:
        ipv4_address: 192.168.100.31
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  ground_station_paris:
    image: baocules/sagsin-agent
    container_name: ground_station_paris
    environment:
      - HOST_NAME=ground_station_paris
    networks:
      topo_net:
        ipv4_address: 192.168.100.32
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  ground_station_moscow:
    image: baocules/sagsin-agent
    container_name: ground_station_moscow 
    environment:
      - HOST_NAME=ground_station_moscow
    networks:
      topo_net:
        ipv4_address: 192.168.100.33
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  mobile_device_tokyo:
    image: baocules/sagsin-agent
    container_name: mobile_device_tokyo
    environment:
      - HOST_NAME=mobile_device_tokyo
    networks:
      topo_net:
        ipv4_address: 192.168.100.34
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  mobile_device_london:
    image: baocules/sagsin-agent
    container_name: mobile_device_london
    environment:
      - HOST_NAME=mobile_device_london
    networks:
      topo_net:
        ipv4_address: 192.168.100.35
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  mobile_device_newyork:
    image: baocules/sagsin-agent
    container_name: mobile_device_newyork
    environment:
      - HOST_NAME=mobile_device_newyork
    networks:
      topo_net:
        ipv4_address: 192.168.100.36
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  mobile_device_singapore:
    image: baocules/sagsin-agent
    container_name: mobile_device_singapore
    environment:
      - HOST_NAME=mobile_device_singapore
    networks:
      topo_net:
        ipv4_address: 192.168.100.37
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  ship_singapore:
    image: baocules/sagsin-agent
    container_name: ship_singapore
    environment:
      - HOST_NAME=ship_singapore
    networks:
      topo_net:
        ipv4_address: 192.168.100.41
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  ship_tokyo:
    image: baocules/sagsin-agent
    container_name: ship_tokyo
    environment:
      - HOST_NAME=ship_tokyo
    networks:
      topo_net:
        ipv4_address: 192.168.100.42
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

  ship_london:
    image: baocules/sagsin-agent
    container_name: ship_london
    environment:
      - HOST_NAME=ship_london
    networks:
      topo_net:
        ipv4_address: 192.168.100.43
    volumes:
      - ./custom_hosts:/etc/hosts
      - ./topology.json:/topology/topology.json:ro

networks:
  topo_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24